languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Zirkus Quartier Franken e.V."

[params]
  description = "Als eingetragener und gemeinnützig anerkannter Verein, wollen wir in der Metropolregion Nürnberg, die Zirkuskünste leben und fördern."
  displayName = "DE"
  isoCode = "de"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_alt.png"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Zirkus Quartier Franken e.V."
  image = "img/round_logo.png"
  links = [
  { facebook = "https://www.facebook.com/profile.php?id=61552224718900" },
  { instagram = "https://www.instagram.com/zirkusquartierfranken_ev" },
  { email = "mailto:info@zirkus-quartier-franken.de"}
]

#  headline = "mehr Zirkus für Franken"
#   bio = "A little bit about you"